Fix dynamic property errorMsg in PaymentDetails resolver
Fixes and issue when the paytrail payment returns with an error
The payment won't crash due to the error below

main.ERROR: Deprecated Functionality: Creation of dynamic property
Paytrail\PaymentServiceGraphQl\Model\Resolver\PaymentDetails\Interceptor::$errorMsg
is deprecated

Also adds the missing dependency of processService that was being used
inside the error condition as well.